import os
import json
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv
import pandas as pd

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

from data_loader import load_data

load_dotenv()

df = load_data()

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0,
    google_api_key=os.getenv("GOOGLE_API_KEY")
)
prompt = ChatPromptTemplate.from_template("""
You are a Titanic passenger dataset analysis assistant.

Dataset columns:
{columns}

Context:
- Each row represents one passenger.
- "People" and "passengers" mean the same thing.
- Survived: 0 = Died, 1 = Survived.
- The dataset contains ONLY passenger information.

CRITICAL RULES:

1. When answering simple analytical questions
   (average, count, percentage, max, min, etc.),
   you must reason about the dataset and provide the
   final numerical answer in plain English.

2. NEVER output Python code.
3. NEVER output expressions like df['Fare'].mean().
4. NEVER output placeholders in brackets.
5. Always provide the computed result directly as text.

6. If the question requires grouping, comparison,
   distribution, or trends, return ONLY this JSON format:

{{
  "plot_required": true,
  "plot_type": "bar | histogram | pie | line | scatter",
  "x_column": "column_name",
  "y_column": "column_name_or_null",
  "filter_condition": "boolean expression usable inside df.query() or null",
  "aggregation": "count | mean | sum | none"
}}

Rules for filter_condition:
- Must be a valid boolean expression for df.query()
- Example: "Age < 18", "Sex == 'male'"
- Do NOT include assignments or transformations
- If no filtering needed, return null

7. If the dataset does not contain the information,
   respond with a short explanation about information.

Return ONLY:
- Plain text answer
OR
- JSON (if plot_required is true)

Never include markdown.

User Question:
{question}
""")

chain = prompt | llm

def handle_intent(question):

    if os.path.exists("output.png"):
        os.remove("output.png")

    response = chain.invoke({
        "columns": df.columns.tolist(),
        "question": question
    })

    content = response.content.strip()

    # If it starts with { assume JSON
    if content.startswith("{"):
        intent = json.loads(content)
        return generate_plot(intent)

    # Otherwise treat as normal text
    return {
        "answer": content,
        "plot_available": False
    }

def generate_plot(intent):

    df_filtered = df

    filter_condition = intent.get("filter_condition")

    if filter_condition:
        try:
            # Only allow safe boolean expressions
            if any(keyword in filter_condition for keyword in ["=", "bins", "labels", "import"]):
                raise ValueError("Invalid filter expression")

            df_filtered = df.query(filter_condition)
        except Exception:
            return {
                "answer": "Invalid filter condition generated by model.",
                "plot_available": False
            }

    x_col = intent.get("x_column")
    y_col = intent.get("y_column")
    agg = intent.get("aggregation")
    plot_type = intent.get("plot_type")


    if agg == "count":
        data = df_filtered[x_col].value_counts()
    elif agg == "mean" and y_col:
        data = df_filtered.groupby(x_col)[y_col].mean()
    else:
        data = df_filtered[x_col]

    # ── Plot Types ─────────────────────────
    plt.figure(figsize=(7, 5))

# ───────── BAR ─────────
    if plot_type == "bar":

        if agg == "count":
            data = df_filtered[x_col].value_counts().sort_index()

        if x_col == "Survived":
            label_map = {0: "Died", 1: "Survived"}
            data.index = data.index.map(label_map)

        ax = data.plot(kind="bar", color="#2E6F95")

        for i, v in enumerate(data.values):
            plt.text(i, v, f"{int(v)}", ha='center', va='bottom')

        plt.xticks(rotation=0)
        plt.ylabel("Count")
        plt.title(f"Distribution of {x_col}")

# ───────── HISTOGRAM ─────────
    elif plot_type == "histogram":

        ax = sns.histplot(data, kde=False, bins=15, color="#2E6F95")

        # Annotate bin counts
        for p in ax.patches:
            height = p.get_height()
            if height > 0:
                ax.annotate(f'{int(height)}',
                            (p.get_x() + p.get_width() / 2., height),
                            ha='center', va='bottom')

        plt.title(f"Histogram of {x_col}")
        plt.xlabel(x_col)
        plt.ylabel("Frequency")

    # ───────── PIE ─────────
    elif plot_type == "pie":

        if agg == "count":
            data = df_filtered[x_col].value_counts()

        def autopct_format(pct):
            total = sum(data.values)
            count = int(round(pct * total / 100.0))
            return f"{pct:.1f}%\n({count})"

        plt.pie(data.values,
                labels=data.index,
                autopct=autopct_format,
                startangle=90)

        plt.title(f"Distribution of {x_col}")

    # ───────── LINE ─────────
    elif plot_type == "line":

        if agg == "mean" and y_col:
            data = df_filtered.groupby(x_col)[y_col].mean()

        ax = data.plot(kind="line", marker="o", color="#2E6F95")

        # Annotate points
        for i, v in enumerate(data.values):
            plt.text(i, v, f"{round(v, 2)}",
                    ha='center', va='bottom')

        plt.title(f"{y_col} Trend by {x_col}")
        plt.xlabel(x_col)
        plt.ylabel(y_col)

    # ───────── SCATTER ─────────
    elif plot_type == "scatter" and y_col:

        x_data = df_filtered[x_col]
        y_data = df_filtered[y_col]

        plt.scatter(x_data, y_data, alpha=0.6, color="#2E6F95")

        plt.title(f"{y_col} vs {x_col}")
        plt.xlabel(x_col)
        plt.ylabel(y_col)

        # Optional: Add correlation text
        if x_data.dtype != "object" and y_data.dtype != "object":
            corr = x_data.corr(y_data)
            plt.text(0.05, 0.95,
                    f"Correlation: {round(corr, 2)}",
                    transform=plt.gca().transAxes,
                    verticalalignment='top')

    plt.tight_layout()
    plt.savefig("output.png")
    plt.close()

    return {
        "answer": "Visualization generated successfully.",
        "plot_available": True
    }